authors = ["<oss@fastly.com>"]
description = "Implements Fanout handlers for WebSockets, SSE, etc."
language = "rust"
manifest_version = 2
name = "Push messaging using Fanout"
service_id = "Mhwp41Rk4BCY3Qm6kubPt0"
